spring.datasource.url=jdbc:postgresql://localhost:5432/cls_db
spring.datasource.username=postgres
spring.datasource.password=user@123
jwt.secret=Wepgv8WLTsgOD87l9pyuMtvGUwYmrUKiOXBRfRQwSkz
cors.allowed-origin=http://localhost:4200