spring.application.name=cls_services

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.org.hibernate.envers.revision_field_name=rev
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revtype
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.autoRegisterListeners=true
spring.jpa.properties.org.hibernate.envers.audit_table_prefix=aud_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=

server.port=${PORT:8081}
jwt.expiration-ms=3600

#spring.profiles.active=dev