spring.application.name=cls_services

spring.datasource.url=jdbc:postgresql://localhost:5432/cls_db
spring.datasource.username=postgres
spring.datasource.password=user@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=false

server.port=8081