spring.application.name=cls_services

spring.datasource.url=jdbc:postgresql://localhost:5432/cls_db
spring.datasource.username=postgres
spring.datasource.password=user@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=false

spring.jpa.properties.org.hibernate.envers.revision_field_name=rev
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revtype
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.autoRegisterListeners=true
spring.jpa.properties.org.hibernate.envers.audit_table_prefix=aud_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=

server.port=8081

jwt.secret=Wepgv8WLTsgOD87l9pyuMtvGUwYmrUKiOXBRfRQwSkz
jwt.expiration-ms=86400000